/**
 * @file models/QuestionCache.js
 * @description Stores question sets generated by users for later reuse in bot lobbies.
 */

'use strict';

const mongoose = require('mongoose');

const questionCacheSchema = new mongoose.Schema({
    _id: String,                          // topic slug
    topic: { type: String, required: true },
    sets: [{
        questions: [{ question: String, options: [String], correct: Number, difficulty: String }],
        createdAt: { type: Number, default: Date.now },
    }],
    updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('QuestionCache', questionCacheSchema);
